documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

frontend:
  - changed-files:
      - any-glob-to-any-file: ['public/**', 'src/frontend/**']

backend:
  - changed-files:
      - any-glob-to-any-file: ['api/**', 'lib/**', 'src/backend/**']
